plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
}

ext {
    archivesBaseName = "BleDemoApp"

    versionMajor = 1

    versionMinor = 0

    versionPatch = 0

    versionBuild = 0
}

android {
    namespace 'com.sunion.ble.demoapp'
    compileSdk 35

    signingConfigs {
        def keystorePropertiesFile
        def keystoreProperties = new Properties()

        BleDemoApp {
            keystorePropertiesFile = rootProject.file("../Config/BleDemoApp/keystore.properties")
            keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    defaultConfig {
        applicationId "com.sunion.ble.demoapp"
        minSdk 26
        targetSdk 35
        versionCode versionMajor * 10000 + versionMinor * 1000 + versionPatch * 100 + versionBuild
        versionName "${versionMajor}.${versionMinor}.${versionPatch}.${versionBuild}"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }

        Properties properties = new Properties()
        properties.load(project.rootProject.file('../Config/BleDemoApp/secure.properties').newDataInputStream()) // load local.properties
        buildConfigField "String", 'BARCODE_KEY', properties.getProperty('BARCODE_KEY')
        buildConfigField "String", 'API_GATEWAY_ENDPOINT', properties.getProperty("API_GATEWAY_ENDPOINT")
        buildConfigField "String", 'API_KEY', properties.getProperty("API_KEY")
        signingConfig signingConfigs.BleDemoApp
        resConfigs "en", "zh-rTW"
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            debuggable false
            multiDexEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // Enables code shrinking, obfuscation, and optimization for only your project's release build type.
            minifyEnabled true
            // Enables resource shrinking, which is performed by the Android Gradle plugin.
            shrinkResources true
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "$archivesBaseName-${variant.baseName}-${variant.versionCode}-${variant.versionName}.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.14'
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {

    implementation project(':core_ble_android')
    implementation "androidx.core:core-ktx:$coreVersion"
    //implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.2.0'
    implementation "androidx.lifecycle:lifecycle-livedata-core:2.6.1"
    implementation 'androidx.activity:activity-compose:1.7.1'

    implementation "androidx.compose.ui:ui:$compose_ui_version"
    implementation "androidx.compose.ui:ui-tooling:$compose_ui_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_ui_version"
    implementation "androidx.compose.material:material:$compose_ui_version"

    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_ui_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_ui_version"

    implementation 'com.google.android.material:material:1.8.0'

    implementation "com.google.dagger:hilt-android:$hilt_version"
    kapt "com.google.dagger:hilt-android-compiler:$hilt_version"
    kapt 'androidx.hilt:hilt-compiler:1.2.0'
    implementation "androidx.hilt:hilt-work:1.2.0"
    implementation "androidx.work:work-runtime-ktx:2.8.1"

    // navigation
    implementation "androidx.navigation:navigation-compose:2.5.3"
    implementation "androidx.hilt:hilt-navigation-compose:1.2.0"

    // log
    implementation "com.jakewharton.timber:timber:$timber_version"

    // RxAndroidBLE
    implementation "com.polidea.rxandroidble2:rxandroidble:1.19.1"

    // Qrcode
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'

    // accompanist
    def accompanist_version = "0.25.0"
    implementation "com.google.accompanist:accompanist-appcompat-theme:$accompanist_version"
    implementation "com.google.accompanist:accompanist-permissions:$accompanist_version"
    implementation "com.google.accompanist:accompanist-pager:$accompanist_version"
    implementation "com.google.accompanist:accompanist-pager-indicators:$accompanist_version"

    // coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.6.4"

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // Http client
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'
    implementation "com.squareup.okhttp3:logging-interceptor:4.12.0"

    // RxJava
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.9.0"
}